# Generated by Django 2.2.9 on 2020-01-15 07:51

import console.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('source', models.CharField(editable=False, max_length=128)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
            ],
            options={
                'db_table': 'event',
            },
            bases=(console.models.ModelEventMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.SmallIntegerField(choices=[(1, 'Programmatic'), (2, 'Managed'), (999, 'System'), (-1, 'Testing'), (-2, 'Unitesting')], default=2)),
                ('active', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('sample', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('managed', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('comments', models.TextField(null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscriber',
            },
        ),
        migrations.CreateModel(
            name='SubscribedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_host', models.CharField(editable=False, max_length=256)),
                ('process_pid', models.CharField(editable=False, max_length=32, null=True)),
                ('process_times', models.IntegerField(default=1, editable=False)),
                ('process_start_time', models.DateTimeField(auto_now_add=True)),
                ('process_end_time', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(default=0, editable=False)),
                ('result', models.TextField(editable=False, null=True)),
                ('event', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed', to='console.Event')),
                ('event_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_events', to='console.EventType')),
                ('publisher', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_publisher_events', to='console.Publisher')),
                ('subscriber', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='console.Subscriber')),
            ],
            options={
                'index_together': {('publisher', 'event_type', 'status'), ('event',)},
                'db_table': 'subscribed_event',
                'unique_together': {('subscriber', 'publisher', 'event_type', 'event')},
            },
        ),
        migrations.AddField(
            model_name='eventtype',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='console.Publisher'),
        ),
        migrations.CreateModel(
            name='EventProcessingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_host', models.CharField(editable=False, max_length=256)),
                ('process_pid', models.CharField(editable=False, max_length=32, null=True)),
                ('process_start_time', models.DateTimeField(editable=False)),
                ('process_end_time', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(editable=False)),
                ('result', models.TextField(editable=False, null=True)),
                ('subscribed_event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='processing_history', to='console.SubscribedEvent')),
            ],
            options={
                'db_table': 'event_processing_history',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='console.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='publisher_events', to='console.Publisher'),
        ),
        migrations.CreateModel(
            name='SubscribedEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed', models.BooleanField(default=True, editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('last_dispatched_time', models.DateTimeField(editable=False, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_event_types', to='console.EventType')),
                ('last_dispatched_event', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.Event')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_publisher_event_types', to='console.Publisher')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='console.Subscriber')),
            ],
            options={
                'unique_together': {('subscriber', 'publisher', 'event_type')},
                'db_table': 'subscribed_event_type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('publisher', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='event',
            index_together={('publisher', 'event_type'), ('publisher',)},
        ),
    ]
