# Generated by Django 2.2.9 on 2020-01-16 06:50

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprocessingmodule',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedeventtype',
            name='event_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='publisher', chained_model_field='publisher', on_delete=django.db.models.deletion.PROTECT, to='console.Publisher'),
        ),
    ]
