# Generated by Django 2.2.9 on 2020-01-13 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200113_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedeventtype',
            name='managed',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='subscribedeventtype',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='subscribedeventtype',
            name='last_dispatched_event',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.Event'),
        ),
        migrations.AlterField(
            model_name='subscribedeventtype',
            name='last_dispatched_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
