# Generated by Django 2.2.9 on 2020-01-13 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20200113_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='process_end_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='process_host',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='process_pid',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='process_start_time',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='result',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='status',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='subscribed_event',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='processing_history', to='console.SubscribedEvent'),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='event',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed', to='console.Event'),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='event_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_events', to='console.EventType'),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='process_end_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='process_host',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='process_pid',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='process_times',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='publisher',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_publisher_events', to='console.Publisher'),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='result',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='subscribedevent',
            name='subscriber',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='console.Subscriber'),
        ),
    ]
