# Generated by Django 2.2.6 on 2020-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20200305_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedeventtype',
            name='replay_failed_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscribedeventtype',
            name='replay_missed_events',
            field=models.BooleanField(default=True),
        ),
    ]
