# Generated by Django 2.2.6 on 2020-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_subscribedeventtype_last_listening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedevent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Succeed'), (-1, 'Failed'), (-2, 'Timeout')], default=0, editable=False),
        ),
    ]
