# Generated by Django 2.2.6 on 2020-03-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_auto_20200305_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprocessinghistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Succeed'), (-1, 'Failed'), (-2, 'Timeout')], editable=False),
        ),
    ]
